version: '3.0'

services:
  app:
    build: .
    volumes:
      - ./auth.env:/usr/src/themoviepredictor/auth.env
    networks:
      - database_net
    # command: tail -f /dev/null
    command: python app5_schedule.py
  database:
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=predictor
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=predictor
    networks:
      - database_net
    volumes: 
      - database_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command:
      --default_authentication_plugin=mysql_native_password

  adminer:
    image: dehy/adminer:latest
    networks: 
      - database_net
    ports:
      - 8080:80

networks:
  database_net:
    driver: bridge

volumes:
  database_data:
