version: '3.0'

services:
  app:
    build: .
    image: python-alpine-custom
    volumes:
      - ./auth.env:/usr/src/themoviepredictor/auth.env
    networks:
      - database_net
    # command: tail -f /dev/null
    command: python app5_schedule.py
  database:
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=predictor
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=predictor
    networks:
      - database_net
    volumes: 
      - database_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command:
      --default_authentication_plugin=mysql_native_password

  adminer:
    image: dehy/adminer:latest
    networks: 
      - database_net
    ports:
      - 8080:80
  
  jupyter:
    image: jupyter-image-custom
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 8888:8888
      - 6006:6006
    volumes:
      - ../../:/usr/src/themoviepredictor
    env_file: 
      - auth.env
    command: /opt/conda/bin/jupyter notebook --notebook-dir=/usr/src/themoviepredictor --ip='0.0.0.0' --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    networks: 
      - database_net

networks:
  database_net:
    driver: bridge

volumes:
  database_data:
